name: Build

on:
  push:
    branches: [develop]
  pull_request: {}
  workflow_dispatch: {}



jobs:
  build:
    name: Build Linux amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make dbgen

