name: Publish

on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}



jobs:
  publish-linux:
    name: Publish Linux amd64
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          ./scripts/ci-build.sh
          ./scripts/ci-release.sh

  publish-macos:
    name: Publish macOS
    runs-on: macos-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          ./scripts/ci-build.sh
          ./scripts/ci-release.sh


